apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: akka-docker-dummy
  name: akka-docker-dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: akka-docker-dummy
  template:
    metadata:
      labels:
        run: akka-docker-dummy
    spec:
      volumes:
      - name: config-data
        emptyDir: {}
      initContainers:
      - name: init-from-keyvault
        image: navicore/keyvaultconfig
        env:
        - name: AZURE_CLIENT_ID
          value: "SET ME"
        - name: AZURE_CLIENT_SECRET
          value: "SET ME"
        - name: AZURE_TENANT_ID
          value: "SET ME"
        - name: KEYVAULT_ID
          value: "/subscriptions/SETME/resourceGroups/SETME/providers/Microsoft.KeyVault/vaults/SETME"
        - name: SECRETS_FILE_LOCATION
          value: "/opt/config/overrides.yaml"
        - name: SECRETS_SPEC
          value: "main.path:MAIN_PATH,main.port:MAIN_PORT"
        volumeMounts:
        - name: config-data
          mountPath: /opt/config
      containers:
      - name: dummy
        image: navicore/akka-docker-dummy
        imagePullPolicy: Always
        volumeMounts:
        - name: config-data
          mountPath: /opt/config
