apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: init-container-demo
  name: init-container-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: init-container-demo
  template:
    metadata:
      labels:
        run: init-container-demo
    spec:
      volumes:
      - name: config-data
        emptyDir: {}
      initContainers:
      - name: init-from-keyvault
        image: navicore/keyvaultconfig
        envFrom:
        - configMapRef:
            name: demo-vault-config
        env:
        - name: SECRETS_FILE_LOCATION
          value: "/opt/config/overrides.yaml"
        - name: SECRETS_SPEC
          # format is a comma delimited list of pairs "config.name:secretName,..."
          # ie: "akka.contrib.persistence.mongodb.mongo.mongouri:PROD_DB_MONGOURI"
          value: "main.path:MAIN_PATH,main.port:MAIN_PORT"
        volumeMounts:
        - name: config-data
          mountPath: /opt/config
      containers:
      - name: dummy-app
        image: navicore/akka-docker-dummy
        env:
        - name: CONFIG_OVERRIDES_URL
          value: "file:///opt/config/overrides.yaml"
        volumeMounts:
        - name: config-data
          mountPath: /opt/config
