apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: init-container-demo
  name: init-container-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: init-container-demo
  template:
    metadata:
      labels:
        run: init-container-demo
    spec:
      volumes:
      - name: config-data
        emptyDir: {}
      initContainers:
      - name: init-from-keyvault
        image: navicore/keyvaultconfig
        envFrom:
        - configMapRef:
            name: demo-vault-config
        env:
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-client-secret
              key: AZURE_CLIENT_SECRET
        volumeMounts:
        - name: config-data
          mountPath: /opt/config
      containers:
      - name: dummy-app
        image: navicore/akka-docker-dummy
        env:
        - name: CONFIG_OVERRIDES_URL
          value: "file:///opt/config/overrides.yaml"
        volumeMounts:
        - name: config-data
          mountPath: /opt/config
