apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: sidecar-container-demo
  name: sidecar-container-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sidecar-container-demo
  template:
    metadata:
      labels:
        run: sidecar-container-demo
    spec:
      containers:
      - name: keyvault-sidecar
        image: navicore/keyvaultconfig:0.1.8
        envFrom:
        - configMapRef:
            name: demo-vault-config
        env:
        - name: IS_SIDECAR
          value: "true"
        - name: SECRETS_SPEC
          # format is a comma delimited list of pairs "config.name:secretName,..."
          # ie: "akka.contrib.persistence.mongodb.mongo.mongouri:PROD_DB_MONGOURI"
          value: "main.path:MAIN_PATH,main.port:MAIN_PORT"
      - name: dummy-app
        image: navicore/akka-docker-dummy:0.1.1
        env:
        - name: CONFIG_OVERRIDES_URL
          value: "http://localhost:8998/config"

