apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: sidecar-container-demo
  name: sidecar-container-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sidecar-container-demo
  template:
    metadata:
      labels:
        run: sidecar-container-demo
    spec:
      containers:
      - name: keyvault-sidecar
        image: navicore/keyvaultconfig:0.1.8
        envFrom:
        - configMapRef:
            name: demo-vault-config
        env:
        - name: IS_SIDECAR
          value: "true"
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-client-secret
              key: AZURE_CLIENT_SECRET
      - name: dummy-app
        image: navicore/akka-docker-dummy:0.1.1
        env:
        - name: CONFIG_OVERRIDES_URL
          value: "http://localhost:8998/config"

